use std::rc::Rc;

use installer::{
    base_installer::BaseInstaller,
    essentials::{Bootloader, Essentials, SuperUserUtility},
    filesystem_tasks::Filesystem,
    pacman::Pacman,
};
use ratatui::widgets::ListState;
use shell_iface::logger::Logger;

pub enum Screens {
    StartScreen,
    Filesystem,
    Pacman,
    Essentials,
    Installing,
    Exiting,
}

pub enum SubScreens {
    None,

    /* Filesystem */
    Partitioning,
    MountBoot,
    MountHome,
    MountRoot,
    EraseEFI,
    EraseHome,
    ConfirmPartitions,

    /* Essentials */
    SetupSwap,
    SelectTimezone,
    SelectLocale,
    SetupHostname,
    SetupRootPassword,
    SetupExtraPrograms,
    SetupBootloader,
    SetupSuperUserUtility,
    SetupUser,
}

/// Stores the app state
pub struct App<'a> {
    /* App render state */
    pub current_screen: Screens,
    pub current_sub_screen: SubScreens,
    pub list_selection: ListState,
    pub error_console: String,

    pub redraw_next_frame: bool,

    /* Lists */
    pub filesystem_drives_list: Rc<Vec<String>>,
    pub filesystem_partitions_list: Rc<Vec<String>>,
    pub reflector_countries: Rc<Vec<&'a str>>,
    pub timezones: Rc<Vec<&'a str>>,
    pub swap_sizes_list: Rc<Vec<usize>>,
    pub locales_list: Rc<Vec<&'a str>>,

    /* Selection and Method parameters */
    pub selected_reflector_country: String,
    pub selected_timezone: String,
    pub selected_locale: String,
    pub selected_encoding: String,
    pub swap_size: usize,
    pub username: String,
    pub password: String,
    pub root_password: String,
    pub hostname: String,

    /* Configuration state */
    pub filesystem: Filesystem<'a>,
    pub base_intaller: BaseInstaller<'a>,
    pub essentials: Essentials<'a>,
    pub pacman: Pacman<'a>,

    /* Progress */
    pub filesystem_setup_complete: bool,
    pub pacman_setup_complete: bool,
    pub essentials_setup_complete: bool,
}

impl<'a> App<'a> {
    pub fn new<'b>(logger: &'b Logger) -> App<'b> {
        App {
            current_screen: Screens::StartScreen,
            current_sub_screen: SubScreens::None,
            list_selection: ListState::default().with_selected(Some(0)),
            error_console: String::new(),
            redraw_next_frame: false,
            filesystem: Filesystem::new(&logger),
            base_intaller: BaseInstaller::new(&logger),
            pacman: Pacman::new(&logger),
            essentials: Essentials::new(&logger, Bootloader::Grub, SuperUserUtility::Sudo),
            filesystem_drives_list: Rc::new(Vec::new()),
            filesystem_partitions_list: Rc::new(Vec::new()),
            filesystem_setup_complete: false,
            pacman_setup_complete: false,
            essentials_setup_complete: false,

            selected_reflector_country: String::new(),
            selected_timezone: String::new(),
            selected_locale: String::new(),
            selected_encoding: String::new(),
            swap_size: 16,
            username: String::new(),
            password: String::new(),
            root_password: String::new(),
            hostname: String::new(),

            swap_sizes_list: Rc::new(vec![1, 2, 4, 8, 16, 32, 64]),
            reflector_countries: Rc::new(vec![
                "India",
                "Australia",
                "Austria",
                "Azerbaijan",
                "Bangladesh",
                "Belarus",
                "Belgium",
                "Bosnia and Herzegovina",
                "Brazil",
                "Bulgaria",
                "Cambodia",
                "Canada",
                "Chile",
                "China",
                "Colombia",
                "Croatia",
                "Czechia",
                "Denmark",
                "Ecuador",
                "Estonia",
                "Finland",
                "France",
                "Georgia",
                "Germany",
                "Greece",
                "Hong Kong",
                "Hungary",
                "Iceland",
                "India",
                "Indonesia",
                "Iran",
                "Israel",
                "Italy",
                "Japan",
                "Kazakhstan",
                "Kenya",
                "Latvia",
                "Lithuania",
                "Luxembourg",
                "Mauritius",
                "Mexico",
                "Moldova",
                "Monaco",
                "Netherlands",
                "New Caledonia",
                "New Zealand",
                "North Macedonia",
                "Norway",
                "Paraguay",
                "Poland",
                "Portugal",
                "Romania",
                "Russia",
                "Réunion",
                "Serbia",
                "Singapore",
                "Slovakia",
                "Slovenia",
                "South Africa",
                "South Korea",
                "Spain",
                "Sweden",
                "Switzerland",
                "Taiwan",
                "Thailand",
                "Türkiye",
                "Ukraine",
                "United Kingdom",
                "United States",
                "Uzbekistan",
                "Vietnam",
            ]),
            timezones: Rc::new(vec![
                "Asia/Kolkata",
                "Africa/Abidjan",
                "Africa/Accra",
                "Africa/Addis_Ababa",
                "Africa/Algiers",
                "Africa/Asmara",
                "Africa/Asmera",
                "Africa/Bamako",
                "Africa/Bangui",
                "Africa/Banjul",
                "Africa/Bissau",
                "Africa/Blantyre",
                "Africa/Brazzaville",
                "Africa/Bujumbura",
                "Africa/Cairo",
                "Africa/Casablanca",
                "Africa/Ceuta",
                "Africa/Conakry",
                "Africa/Dakar",
                "Africa/Dar_es_Salaam",
                "Africa/Djibouti",
                "Africa/Douala",
                "Africa/El_Aaiun",
                "Africa/Freetown",
                "Africa/Gaborone",
                "Africa/Harare",
                "Africa/Johannesburg",
                "Africa/Juba",
                "Africa/Kampala",
                "Africa/Khartoum",
                "Africa/Kigali",
                "Africa/Kinshasa",
                "Africa/Lagos",
                "Africa/Libreville",
                "Africa/Lome",
                "Africa/Luanda",
                "Africa/Lubumbashi",
                "Africa/Lusaka",
                "Africa/Malabo",
                "Africa/Maputo",
                "Africa/Maseru",
                "Africa/Mbabane",
                "Africa/Mogadishu",
                "Africa/Monrovia",
                "Africa/Nairobi",
                "Africa/Ndjamena",
                "Africa/Niamey",
                "Africa/Nouakchott",
                "Africa/Ouagadougou",
                "Africa/Porto-Novo",
                "Africa/Sao_Tome",
                "Africa/Timbuktu",
                "Africa/Tripoli",
                "Africa/Tunis",
                "Africa/Windhoek",
                "America/Adak",
                "America/Anchorage",
                "America/Anguilla",
                "America/Antigua",
                "America/Araguaina",
                "America/Argentina/Buenos_Aires",
                "America/Argentina/Catamarca",
                "America/Argentina/ComodRivadavia",
                "America/Argentina/Cordoba",
                "America/Argentina/Jujuy",
                "America/Argentina/La_Rioja",
                "America/Argentina/Mendoza",
                "America/Argentina/Rio_Gallegos",
                "America/Argentina/Salta",
                "America/Argentina/San_Juan",
                "America/Argentina/San_Luis",
                "America/Argentina/Tucuman",
                "America/Argentina/Ushuaia",
                "America/Aruba",
                "America/Asuncion",
                "America/Atikokan",
                "America/Atka",
                "America/Bahia",
                "America/Bahia_Banderas",
                "America/Barbados",
                "America/Belem",
                "America/Belize",
                "America/Blanc-Sablon",
                "America/Boa_Vista",
                "America/Bogota",
                "America/Boise",
                "America/Buenos_Aires",
                "America/Cambridge_Bay",
                "America/Campo_Grande",
                "America/Cancun",
                "America/Caracas",
                "America/Catamarca",
                "America/Cayenne",
                "America/Cayman",
                "America/Chicago",
                "America/Chihuahua",
                "America/Ciudad_Juarez",
                "America/Coral_Harbour",
                "America/Cordoba",
                "America/Costa_Rica",
                "America/Creston",
                "America/Cuiaba",
                "America/Curacao",
                "America/Danmarkshavn",
                "America/Dawson",
                "America/Dawson_Creek",
                "America/Denver",
                "America/Detroit",
                "America/Dominica",
                "America/Edmonton",
                "America/Eirunepe",
                "America/El_Salvador",
                "America/Ensenada",
                "America/Fort_Nelson",
                "America/Fort_Wayne",
                "America/Fortaleza",
                "America/Glace_Bay",
                "America/Godthab",
                "America/Goose_Bay",
                "America/Grand_Turk",
                "America/Grenada",
                "America/Guadeloupe",
                "America/Guatemala",
                "America/Guayaquil",
                "America/Guyana",
                "America/Halifax",
                "America/Havana",
                "America/Hermosillo",
                "America/Indiana/Indianapolis",
                "America/Indiana/Knox",
                "America/Indiana/Marengo",
                "America/Indiana/Petersburg",
                "America/Indiana/Tell_City",
                "America/Indiana/Vevay",
                "America/Indiana/Vincennes",
                "America/Indiana/Winamac",
                "America/Indianapolis",
                "America/Inuvik",
                "America/Iqaluit",
                "America/Jamaica",
                "America/Jujuy",
                "America/Juneau",
                "America/Kentucky/Louisville",
                "America/Kentucky/Monticello",
                "America/Knox_IN",
                "America/Kralendijk",
                "America/La_Paz",
                "America/Lima",
                "America/Los_Angeles",
                "America/Louisville",
                "America/Lower_Princes",
                "America/Maceio",
                "America/Managua",
                "America/Manaus",
                "America/Marigot",
                "America/Martinique",
                "America/Matamoros",
                "America/Mazatlan",
                "America/Mendoza",
                "America/Menominee",
                "America/Merida",
                "America/Metlakatla",
                "America/Mexico_City",
                "America/Miquelon",
                "America/Moncton",
                "America/Monterrey",
                "America/Montevideo",
                "America/Montreal",
                "America/Montserrat",
                "America/Nassau",
                "America/New_York",
                "America/Nipigon",
                "America/Nome",
                "America/Noronha",
                "America/North_Dakota/Beulah",
                "America/North_Dakota/Center",
                "America/North_Dakota/New_Salem",
                "America/Nuuk",
                "America/Ojinaga",
                "America/Panama",
                "America/Pangnirtung",
                "America/Paramaribo",
                "America/Phoenix",
                "America/Port-au-Prince",
                "America/Port_of_Spain",
                "America/Porto_Acre",
                "America/Porto_Velho",
                "America/Puerto_Rico",
                "America/Punta_Arenas",
                "America/Rainy_River",
                "America/Rankin_Inlet",
                "America/Recife",
                "America/Regina",
                "America/Resolute",
                "America/Rio_Branco",
                "America/Rosario",
                "America/Santa_Isabel",
                "America/Santarem",
                "America/Santiago",
                "America/Santo_Domingo",
                "America/Sao_Paulo",
                "America/Scoresbysund",
                "America/Shiprock",
                "America/Sitka",
                "America/St_Barthelemy",
                "America/St_Johns",
                "America/St_Kitts",
                "America/St_Lucia",
                "America/St_Thomas",
                "America/St_Vincent",
                "America/Swift_Current",
                "America/Tegucigalpa",
                "America/Thule",
                "America/Thunder_Bay",
                "America/Tijuana",
                "America/Toronto",
                "America/Tortola",
                "America/Vancouver",
                "America/Virgin",
                "America/Whitehorse",
                "America/Winnipeg",
                "America/Yakutat",
                "America/Yellowknife",
                "Antarctica/Casey",
                "Antarctica/Davis",
                "Antarctica/DumontDUrville",
                "Antarctica/Macquarie",
                "Antarctica/Mawson",
                "Antarctica/McMurdo",
                "Antarctica/Palmer",
                "Antarctica/Rothera",
                "Antarctica/South_Pole",
                "Antarctica/Syowa",
                "Antarctica/Troll",
                "Antarctica/Vostok",
                "Arctic/Longyearbyen",
                "Asia/Aden",
                "Asia/Almaty",
                "Asia/Amman",
                "Asia/Anadyr",
                "Asia/Aqtau",
                "Asia/Aqtobe",
                "Asia/Ashgabat",
                "Asia/Ashkhabad",
                "Asia/Atyrau",
                "Asia/Baghdad",
                "Asia/Bahrain",
                "Asia/Baku",
                "Asia/Bangkok",
                "Asia/Barnaul",
                "Asia/Beirut",
                "Asia/Bishkek",
                "Asia/Brunei",
                "Asia/Calcutta",
                "Asia/Chita",
                "Asia/Choibalsan",
                "Asia/Chongqing",
                "Asia/Chungking",
                "Asia/Colombo",
                "Asia/Dacca",
                "Asia/Damascus",
                "Asia/Dhaka",
                "Asia/Dili",
                "Asia/Dubai",
                "Asia/Dushanbe",
                "Asia/Famagusta",
                "Asia/Gaza",
                "Asia/Harbin",
                "Asia/Hebron",
                "Asia/Ho_Chi_Minh",
                "Asia/Hong_Kong",
                "Asia/Hovd",
                "Asia/Irkutsk",
                "Asia/Istanbul",
                "Asia/Jakarta",
                "Asia/Jayapura",
                "Asia/Jerusalem",
                "Asia/Kabul",
                "Asia/Kamchatka",
                "Asia/Karachi",
                "Asia/Kashgar",
                "Asia/Kathmandu",
                "Asia/Katmandu",
                "Asia/Khandyga",
                "Asia/Kolkata",
                "Asia/Krasnoyarsk",
                "Asia/Kuala_Lumpur",
                "Asia/Kuching",
                "Asia/Kuwait",
                "Asia/Macao",
                "Asia/Macau",
                "Asia/Magadan",
                "Asia/Makassar",
                "Asia/Manila",
                "Asia/Muscat",
                "Asia/Nicosia",
                "Asia/Novokuznetsk",
                "Asia/Novosibirsk",
                "Asia/Omsk",
                "Asia/Oral",
                "Asia/Phnom_Penh",
                "Asia/Pontianak",
                "Asia/Pyongyang",
                "Asia/Qatar",
                "Asia/Qostanay",
                "Asia/Qyzylorda",
                "Asia/Rangoon",
                "Asia/Riyadh",
                "Asia/Saigon",
                "Asia/Sakhalin",
                "Asia/Samarkand",
                "Asia/Seoul",
                "Asia/Shanghai",
                "Asia/Singapore",
                "Asia/Srednekolymsk",
                "Asia/Taipei",
                "Asia/Tashkent",
                "Asia/Tbilisi",
                "Asia/Tehran",
                "Asia/Tel_Aviv",
                "Asia/Thimbu",
                "Asia/Thimphu",
                "Asia/Tokyo",
                "Asia/Tomsk",
                "Asia/Ujung_Pandang",
                "Asia/Ulaanbaatar",
                "Asia/Ulan_Bator",
                "Asia/Urumqi",
                "Asia/Ust-Nera",
                "Asia/Vientiane",
                "Asia/Vladivostok",
                "Asia/Yakutsk",
                "Asia/Yangon",
                "Asia/Yekaterinburg",
                "Asia/Yerevan",
                "Atlantic/Azores",
                "Atlantic/Bermuda",
                "Atlantic/Canary",
                "Atlantic/Cape_Verde",
                "Atlantic/Faeroe",
                "Atlantic/Faroe",
                "Atlantic/Jan_Mayen",
                "Atlantic/Madeira",
                "Atlantic/Reykjavik",
                "Atlantic/South_Georgia",
                "Atlantic/St_Helena",
                "Atlantic/Stanley",
                "Australia/ACT",
                "Australia/Adelaide",
                "Australia/Brisbane",
                "Australia/Broken_Hill",
                "Australia/Canberra",
                "Australia/Currie",
                "Australia/Darwin",
                "Australia/Eucla",
                "Australia/Hobart",
                "Australia/LHI",
                "Australia/Lindeman",
                "Australia/Lord_Howe",
                "Australia/Melbourne",
                "Australia/NSW",
                "Australia/North",
                "Australia/Perth",
                "Australia/Queensland",
                "Australia/South",
                "Australia/Sydney",
                "Australia/Tasmania",
                "Australia/Victoria",
                "Australia/West",
                "Australia/Yancowinna",
                "Brazil/Acre",
                "Brazil/DeNoronha",
                "Brazil/East",
                "Brazil/West",
                "CET",
                "CST6CDT",
                "Canada/Atlantic",
                "Canada/Central",
                "Canada/Eastern",
                "Canada/Mountain",
                "Canada/Newfoundland",
                "Canada/Pacific",
                "Canada/Saskatchewan",
                "Canada/Yukon",
                "Chile/Continental",
                "Chile/EasterIsland",
                "Cuba",
                "EET",
                "EST",
                "EST5EDT",
                "Egypt",
                "Eire",
                "Etc/GMT",
                "Etc/GMT+0",
                "Etc/GMT+1",
                "Etc/GMT+10",
                "Etc/GMT+11",
                "Etc/GMT+12",
                "Etc/GMT+2",
                "Etc/GMT+3",
                "Etc/GMT+4",
                "Etc/GMT+5",
                "Etc/GMT+6",
                "Etc/GMT+7",
                "Etc/GMT+8",
                "Etc/GMT+9",
                "Etc/GMT-0",
                "Etc/GMT-1",
                "Etc/GMT-10",
                "Etc/GMT-11",
                "Etc/GMT-12",
                "Etc/GMT-13",
                "Etc/GMT-14",
                "Etc/GMT-2",
                "Etc/GMT-3",
                "Etc/GMT-4",
                "Etc/GMT-5",
                "Etc/GMT-6",
                "Etc/GMT-7",
                "Etc/GMT-8",
                "Etc/GMT-9",
                "Etc/GMT0",
                "Etc/Greenwich",
                "Etc/UCT",
                "Etc/UTC",
                "Etc/Universal",
                "Etc/Zulu",
                "Europe/Amsterdam",
                "Europe/Andorra",
                "Europe/Astrakhan",
                "Europe/Athens",
                "Europe/Belfast",
                "Europe/Belgrade",
                "Europe/Berlin",
                "Europe/Bratislava",
                "Europe/Brussels",
                "Europe/Bucharest",
                "Europe/Budapest",
                "Europe/Busingen",
                "Europe/Chisinau",
                "Europe/Copenhagen",
                "Europe/Dublin",
                "Europe/Gibraltar",
                "Europe/Guernsey",
                "Europe/Helsinki",
                "Europe/Isle_of_Man",
                "Europe/Istanbul",
                "Europe/Jersey",
                "Europe/Kaliningrad",
                "Europe/Kiev",
                "Europe/Kirov",
                "Europe/Kyiv",
                "Europe/Lisbon",
                "Europe/Ljubljana",
                "Europe/London",
                "Europe/Luxembourg",
                "Europe/Madrid",
                "Europe/Malta",
                "Europe/Mariehamn",
                "Europe/Minsk",
                "Europe/Monaco",
                "Europe/Moscow",
                "Europe/Nicosia",
                "Europe/Oslo",
                "Europe/Paris",
                "Europe/Podgorica",
                "Europe/Prague",
                "Europe/Riga",
                "Europe/Rome",
                "Europe/Samara",
                "Europe/San_Marino",
                "Europe/Sarajevo",
                "Europe/Saratov",
                "Europe/Simferopol",
                "Europe/Skopje",
                "Europe/Sofia",
                "Europe/Stockholm",
                "Europe/Tallinn",
                "Europe/Tirane",
                "Europe/Tiraspol",
                "Europe/Ulyanovsk",
                "Europe/Uzhgorod",
                "Europe/Vaduz",
                "Europe/Vatican",
                "Europe/Vienna",
                "Europe/Vilnius",
                "Europe/Volgograd",
                "Europe/Warsaw",
                "Europe/Zagreb",
                "Europe/Zaporozhye",
                "Europe/Zurich",
                "Factory",
                "GB",
                "GB-Eire",
                "GMT",
                "GMT+0",
                "GMT-0",
                "GMT0",
                "Greenwich",
                "HST",
                "Hongkong",
                "Iceland",
                "Indian/Antananarivo",
                "Indian/Chagos",
                "Indian/Christmas",
                "Indian/Cocos",
                "Indian/Comoro",
                "Indian/Kerguelen",
                "Indian/Mahe",
                "Indian/Maldives",
                "Indian/Mauritius",
                "Indian/Mayotte",
                "Indian/Reunion",
                "Iran",
                "Israel",
                "Jamaica",
                "Japan",
                "Kwajalein",
                "Libya",
                "MET",
                "MST",
                "MST7MDT",
                "Mexico/BajaNorte",
                "Mexico/BajaSur",
                "Mexico/General",
                "NZ",
                "NZ-CHAT",
                "Navajo",
                "PRC",
                "PST8PDT",
                "Pacific/Apia",
                "Pacific/Auckland",
                "Pacific/Bougainville",
                "Pacific/Chatham",
                "Pacific/Chuuk",
                "Pacific/Easter",
                "Pacific/Efate",
                "Pacific/Enderbury",
                "Pacific/Fakaofo",
                "Pacific/Fiji",
                "Pacific/Funafuti",
                "Pacific/Galapagos",
                "Pacific/Gambier",
                "Pacific/Guadalcanal",
                "Pacific/Guam",
                "Pacific/Honolulu",
                "Pacific/Johnston",
                "Pacific/Kanton",
                "Pacific/Kiritimati",
                "Pacific/Kosrae",
                "Pacific/Kwajalein",
                "Pacific/Majuro",
                "Pacific/Marquesas",
                "Pacific/Midway",
                "Pacific/Nauru",
                "Pacific/Niue",
                "Pacific/Norfolk",
                "Pacific/Noumea",
                "Pacific/Pago_Pago",
                "Pacific/Palau",
                "Pacific/Pitcairn",
                "Pacific/Pohnpei",
                "Pacific/Ponape",
                "Pacific/Port_Moresby",
                "Pacific/Rarotonga",
                "Pacific/Saipan",
                "Pacific/Samoa",
                "Pacific/Tahiti",
                "Pacific/Tarawa",
                "Pacific/Tongatapu",
                "Pacific/Truk",
                "Pacific/Wake",
                "Pacific/Wallis",
                "Pacific/Yap",
                "Poland",
                "Portugal",
                "ROC",
                "ROK",
                "Singapore",
                "Turkey",
                "UCT",
                "US/Alaska",
                "US/Aleutian",
                "US/Arizona",
                "US/Central",
                "US/East-Indiana",
                "US/Eastern",
                "US/Hawaii",
                "US/Indiana-Starke",
                "US/Michigan",
                "US/Mountain",
                "US/Pacific",
                "US/Samoa",
                "UTC",
                "Universal",
                "W-SU",
                "WET",
                "Zulu",
            ]),
            locales_list: Rc::new(vec![
                "en_US.UTF-8 UTF-8",
                "en_IN UTF-8",
                "aa_DJ.UTF-8 UTF-8",
                "aa_DJ ISO-8859-1",
                "aa_ER UTF-8",
                "aa_ER@saaho UTF-8",
                "aa_ET UTF-8",
                "af_ZA.UTF-8 UTF-8",
                "af_ZA ISO-8859-1",
                "agr_PE UTF-8",
                "ak_GH UTF-8",
                "am_ET UTF-8",
                "an_ES.UTF-8 UTF-8",
                "an_ES ISO-8859-15",
                "anp_IN UTF-8",
                "ar_AE.UTF-8 UTF-8",
                "ar_AE ISO-8859-6",
                "ar_BH.UTF-8 UTF-8",
                "ar_BH ISO-8859-6",
                "ar_DZ.UTF-8 UTF-8",
                "ar_DZ ISO-8859-6",
                "ar_EG.UTF-8 UTF-8",
                "ar_EG ISO-8859-6",
                "ar_IN UTF-8",
                "ar_IQ.UTF-8 UTF-8",
                "ar_IQ ISO-8859-6",
                "ar_JO.UTF-8 UTF-8",
                "ar_JO ISO-8859-6",
                "ar_KW.UTF-8 UTF-8",
                "ar_KW ISO-8859-6",
                "ar_LB.UTF-8 UTF-8",
                "ar_LB ISO-8859-6",
                "ar_LY.UTF-8 UTF-8",
                "ar_LY ISO-8859-6",
                "ar_MA.UTF-8 UTF-8",
                "ar_MA ISO-8859-6",
                "ar_OM.UTF-8 UTF-8",
                "ar_OM ISO-8859-6",
                "ar_QA.UTF-8 UTF-8",
                "ar_QA ISO-8859-6",
                "ar_SA.UTF-8 UTF-8",
                "ar_SA ISO-8859-6",
                "ar_SD.UTF-8 UTF-8",
                "ar_SD ISO-8859-6",
                "ar_SS UTF-8",
                "ar_SY.UTF-8 UTF-8",
                "ar_SY ISO-8859-6",
                "ar_TN.UTF-8 UTF-8",
                "ar_TN ISO-8859-6",
                "ar_YE.UTF-8 UTF-8",
                "ar_YE ISO-8859-6",
                "ayc_PE UTF-8",
                "az_AZ UTF-8",
                "az_IR UTF-8",
                "as_IN UTF-8",
                "ast_ES.UTF-8 UTF-8",
                "ast_ES ISO-8859-15",
                "be_BY.UTF-8 UTF-8",
                "be_BY CP1251",
                "be_BY@latin UTF-8",
                "bem_ZM UTF-8",
                "ber_DZ UTF-8",
                "ber_MA UTF-8",
                "bg_BG.UTF-8 UTF-8",
                "bg_BG CP1251",
                "bhb_IN.UTF-8 UTF-8",
                "bho_IN UTF-8",
                "bho_NP UTF-8",
                "bi_VU UTF-8",
                "bn_BD UTF-8",
                "bn_IN UTF-8",
                "bo_CN UTF-8",
                "bo_IN UTF-8",
                "br_FR.UTF-8 UTF-8",
                "br_FR ISO-8859-1",
                "br_FR@euro ISO-8859-15",
                "brx_IN UTF-8",
                "bs_BA.UTF-8 UTF-8",
                "bs_BA ISO-8859-2",
                "byn_ER UTF-8",
                "ca_AD.UTF-8 UTF-8",
                "ca_AD ISO-8859-15",
                "ca_ES.UTF-8 UTF-8",
                "ca_ES ISO-8859-1",
                "ca_ES@euro ISO-8859-15",
                "ca_ES@valencia UTF-8",
                "ca_FR.UTF-8 UTF-8",
                "ca_FR ISO-8859-15",
                "ca_IT.UTF-8 UTF-8",
                "ca_IT ISO-8859-15",
                "ce_RU UTF-8",
                "chr_US UTF-8",
                "ckb_IQ UTF-8",
                "cmn_TW UTF-8",
                "crh_UA UTF-8",
                "cs_CZ.UTF-8 UTF-8",
                "cs_CZ ISO-8859-2",
                "csb_PL UTF-8",
                "cv_RU UTF-8",
                "cy_GB.UTF-8 UTF-8",
                "cy_GB ISO-8859-14",
                "da_DK.UTF-8 UTF-8",
                "da_DK ISO-8859-1",
                "de_AT.UTF-8 UTF-8",
                "de_AT ISO-8859-1",
                "de_AT@euro ISO-8859-15",
                "de_BE.UTF-8 UTF-8",
                "de_BE ISO-8859-1",
                "de_BE@euro ISO-8859-15",
                "de_CH.UTF-8 UTF-8",
                "de_CH ISO-8859-1",
                "de_DE.UTF-8 UTF-8",
                "de_DE ISO-8859-1",
                "de_DE@euro ISO-8859-15",
                "de_IT.UTF-8 UTF-8",
                "de_IT ISO-8859-1",
                "de_LI.UTF-8 UTF-8",
                "de_LU.UTF-8 UTF-8",
                "de_LU ISO-8859-1",
                "de_LU@euro ISO-8859-15",
                "doi_IN UTF-8",
                "dsb_DE UTF-8",
                "dv_MV UTF-8",
                "dz_BT UTF-8",
                "el_GR.UTF-8 UTF-8",
                "el_GR ISO-8859-7",
                "el_GR@euro ISO-8859-7",
                "el_CY.UTF-8 UTF-8",
                "el_CY ISO-8859-7",
                "en_AG UTF-8",
                "en_AU.UTF-8 UTF-8",
                "en_AU ISO-8859-1",
                "en_BW.UTF-8 UTF-8",
                "en_BW ISO-8859-1",
                "en_CA.UTF-8 UTF-8",
                "en_CA ISO-8859-1",
                "en_DK.UTF-8 UTF-8",
                "en_DK ISO-8859-1",
                "en_GB.UTF-8 UTF-8",
                "en_GB ISO-8859-1",
                "en_HK.UTF-8 UTF-8",
                "en_HK ISO-8859-1",
                "en_IE.UTF-8 UTF-8",
                "en_IE ISO-8859-1",
                "en_IE@euro ISO-8859-15",
                "en_IL UTF-8",
                "en_IN UTF-8",
                "en_NG UTF-8",
                "en_NZ.UTF-8 UTF-8",
                "en_NZ ISO-8859-1",
                "en_PH.UTF-8 UTF-8",
                "en_PH ISO-8859-1",
                "en_SC.UTF-8 UTF-8",
                "en_SG.UTF-8 UTF-8",
                "en_SG ISO-8859-1",
                "en_US.UTF-8 UTF-8",
                "en_US ISO-8859-1",
                "en_ZA.UTF-8 UTF-8",
                "en_ZA ISO-8859-1",
                "en_ZM UTF-8",
                "en_ZW.UTF-8 UTF-8",
                "en_ZW ISO-8859-1",
                "eo UTF-8",
                "es_AR.UTF-8 UTF-8",
                "es_AR ISO-8859-1",
                "es_BO.UTF-8 UTF-8",
                "es_BO ISO-8859-1",
                "es_CL.UTF-8 UTF-8",
                "es_CL ISO-8859-1",
                "es_CO.UTF-8 UTF-8",
                "es_CO ISO-8859-1",
                "es_CR.UTF-8 UTF-8",
                "es_CR ISO-8859-1",
                "es_CU UTF-8",
                "es_DO.UTF-8 UTF-8",
                "es_DO ISO-8859-1",
                "es_EC.UTF-8 UTF-8",
                "es_EC ISO-8859-1",
                "es_ES.UTF-8 UTF-8",
                "es_ES ISO-8859-1",
                "es_ES@euro ISO-8859-15",
                "es_GT.UTF-8 UTF-8",
                "es_GT ISO-8859-1",
                "es_HN.UTF-8 UTF-8",
                "es_HN ISO-8859-1",
                "es_MX.UTF-8 UTF-8",
                "es_MX ISO-8859-1",
                "es_NI.UTF-8 UTF-8",
                "es_NI ISO-8859-1",
                "es_PA.UTF-8 UTF-8",
                "es_PA ISO-8859-1",
                "es_PE.UTF-8 UTF-8",
                "es_PE ISO-8859-1",
                "es_PR.UTF-8 UTF-8",
                "es_PR ISO-8859-1",
                "es_PY.UTF-8 UTF-8",
                "es_PY ISO-8859-1",
                "es_SV.UTF-8 UTF-8",
                "es_SV ISO-8859-1",
                "es_US.UTF-8 UTF-8",
                "es_US ISO-8859-1",
                "es_UY.UTF-8 UTF-8",
                "es_UY ISO-8859-1",
                "es_VE.UTF-8 UTF-8",
                "es_VE ISO-8859-1",
                "et_EE.UTF-8 UTF-8",
                "et_EE ISO-8859-1",
                "et_EE.ISO-8859-15 ISO-8859-15",
                "eu_ES.UTF-8 UTF-8",
                "eu_ES ISO-8859-1",
                "eu_ES@euro ISO-8859-15",
                "fa_IR UTF-8",
                "ff_SN UTF-8",
                "fi_FI.UTF-8 UTF-8",
                "fi_FI ISO-8859-1",
                "fi_FI@euro ISO-8859-15",
                "fil_PH UTF-8",
                "fo_FO.UTF-8 UTF-8",
                "fo_FO ISO-8859-1",
                "fr_BE.UTF-8 UTF-8",
                "fr_BE ISO-8859-1",
                "fr_BE@euro ISO-8859-15",
                "fr_CA.UTF-8 UTF-8",
                "fr_CA ISO-8859-1",
                "fr_CH.UTF-8 UTF-8",
                "fr_CH ISO-8859-1",
                "fr_FR.UTF-8 UTF-8",
                "fr_FR ISO-8859-1",
                "fr_FR@euro ISO-8859-15",
                "fr_LU.UTF-8 UTF-8",
                "fr_LU ISO-8859-1",
                "fr_LU@euro ISO-8859-15",
                "fur_IT UTF-8",
                "fy_NL UTF-8",
                "fy_DE UTF-8",
                "ga_IE.UTF-8 UTF-8",
                "ga_IE ISO-8859-1",
                "ga_IE@euro ISO-8859-15",
                "gd_GB.UTF-8 UTF-8",
                "gd_GB ISO-8859-15",
                "gez_ER UTF-8",
                "gez_ER@abegede UTF-8",
                "gez_ET UTF-8",
                "gez_ET@abegede UTF-8",
                "gl_ES.UTF-8 UTF-8",
                "gl_ES ISO-8859-1",
                "gl_ES@euro ISO-8859-15",
                "gu_IN UTF-8",
                "gv_GB.UTF-8 UTF-8",
                "gv_GB ISO-8859-1",
                "ha_NG UTF-8",
                "hak_TW UTF-8",
                "he_IL.UTF-8 UTF-8",
                "he_IL ISO-8859-8",
                "hi_IN UTF-8",
                "hif_FJ UTF-8",
                "hne_IN UTF-8",
                "hr_HR.UTF-8 UTF-8",
                "hr_HR ISO-8859-2",
                "hsb_DE ISO-8859-2",
                "hsb_DE.UTF-8 UTF-8",
                "ht_HT UTF-8",
                "hu_HU.UTF-8 UTF-8",
                "hu_HU ISO-8859-2",
                "hy_AM UTF-8",
                "hy_AM.ARMSCII-8 ARMSCII-8",
                "ia_FR UTF-8",
                "id_ID.UTF-8 UTF-8",
                "id_ID ISO-8859-1",
                "ig_NG UTF-8",
                "ik_CA UTF-8",
                "is_IS.UTF-8 UTF-8",
                "is_IS ISO-8859-1",
                "it_CH.UTF-8 UTF-8",
                "it_CH ISO-8859-1",
                "it_IT.UTF-8 UTF-8",
                "it_IT ISO-8859-1",
                "it_IT@euro ISO-8859-15",
                "iu_CA UTF-8",
                "ja_JP.EUC-JP EUC-JP",
                "ja_JP.UTF-8 UTF-8",
                "ka_GE.UTF-8 UTF-8",
                "ka_GE GEORGIAN-PS",
                "kab_DZ UTF-8",
                "kk_KZ.UTF-8 UTF-8",
                "kk_KZ PT154",
                "kl_GL.UTF-8 UTF-8",
                "kl_GL ISO-8859-1",
                "km_KH UTF-8",
                "kn_IN UTF-8",
                "ko_KR.EUC-KR EUC-KR",
                "ko_KR.UTF-8 UTF-8",
                "kok_IN UTF-8",
                "ks_IN UTF-8",
                "ks_IN@devanagari UTF-8",
                "ku_TR.UTF-8 UTF-8",
                "ku_TR ISO-8859-9",
                "kw_GB.UTF-8 UTF-8",
                "kw_GB ISO-8859-1",
                "ky_KG UTF-8",
                "lb_LU UTF-8",
                "lg_UG.UTF-8 UTF-8",
                "lg_UG ISO-8859-10",
                "li_BE UTF-8",
                "li_NL UTF-8",
                "lij_IT UTF-8",
                "ln_CD UTF-8",
                "lo_LA UTF-8",
                "lt_LT.UTF-8 UTF-8",
                "lt_LT ISO-8859-13",
                "lv_LV.UTF-8 UTF-8",
                "lv_LV ISO-8859-13",
                "lzh_TW UTF-8",
                "mag_IN UTF-8",
                "mai_IN UTF-8",
                "mai_NP UTF-8",
                "mfe_MU UTF-8",
                "mg_MG.UTF-8 UTF-8",
                "mg_MG ISO-8859-15",
                "mhr_RU UTF-8",
                "mi_NZ.UTF-8 UTF-8",
                "mi_NZ ISO-8859-13",
                "miq_NI UTF-8",
                "mjw_IN UTF-8",
                "mk_MK.UTF-8 UTF-8",
                "mk_MK ISO-8859-5",
                "ml_IN UTF-8",
                "mn_MN UTF-8",
                "mni_IN UTF-8",
                "mnw_MM UTF-8",
                "mr_IN UTF-8",
                "ms_MY.UTF-8 UTF-8",
                "ms_MY ISO-8859-1",
                "mt_MT.UTF-8 UTF-8",
                "mt_MT ISO-8859-3",
                "my_MM UTF-8",
                "nan_TW UTF-8",
                "nan_TW@latin UTF-8",
                "nb_NO.UTF-8 UTF-8",
                "nb_NO ISO-8859-1",
                "nds_DE UTF-8",
                "nds_NL UTF-8",
                "ne_NP UTF-8",
                "nhn_MX UTF-8",
                "niu_NU UTF-8",
                "niu_NZ UTF-8",
                "nl_AW UTF-8",
                "nl_BE.UTF-8 UTF-8",
                "nl_BE ISO-8859-1",
                "nl_BE@euro ISO-8859-15",
                "nl_NL.UTF-8 UTF-8",
                "nl_NL ISO-8859-1",
                "nl_NL@euro ISO-8859-15",
                "nn_NO.UTF-8 UTF-8",
                "nn_NO ISO-8859-1",
                "nr_ZA UTF-8",
                "nso_ZA UTF-8",
                "oc_FR.UTF-8 UTF-8",
                "oc_FR ISO-8859-1",
                "om_ET UTF-8",
                "om_KE.UTF-8 UTF-8",
                "om_KE ISO-8859-1",
                "or_IN UTF-8",
                "os_RU UTF-8",
                "pa_IN UTF-8",
                "pa_PK UTF-8",
                "pap_AW UTF-8",
                "pap_CW UTF-8",
                "pl_PL.UTF-8 UTF-8",
                "pl_PL ISO-8859-2",
                "ps_AF UTF-8",
                "pt_BR.UTF-8 UTF-8",
                "pt_BR ISO-8859-1",
                "pt_PT.UTF-8 UTF-8",
                "pt_PT ISO-8859-1",
                "pt_PT@euro ISO-8859-15",
                "quz_PE UTF-8",
                "raj_IN UTF-8",
                "rif_MA UTF-8",
                "ro_RO.UTF-8 UTF-8",
                "ro_RO ISO-8859-2",
                "ru_RU.KOI8-R KOI8-R",
                "ru_RU.UTF-8 UTF-8",
                "ru_RU ISO-8859-5",
                "ru_UA.UTF-8 UTF-8",
                "ru_UA KOI8-U",
                "rw_RW UTF-8",
                "sa_IN UTF-8",
                "sah_RU UTF-8",
                "sat_IN UTF-8",
                "sc_IT UTF-8",
                "sd_IN UTF-8",
                "sd_IN@devanagari UTF-8",
                "se_NO UTF-8",
                "sgs_LT UTF-8",
                "shn_MM UTF-8",
                "shs_CA UTF-8",
                "si_LK UTF-8",
                "sid_ET UTF-8",
                "sk_SK.UTF-8 UTF-8",
                "sk_SK ISO-8859-2",
                "sl_SI.UTF-8 UTF-8",
                "sl_SI ISO-8859-2",
                "sm_WS UTF-8",
                "so_DJ.UTF-8 UTF-8",
                "so_DJ ISO-8859-1",
                "so_ET UTF-8",
                "so_KE.UTF-8 UTF-8",
                "so_KE ISO-8859-1",
                "so_SO.UTF-8 UTF-8",
                "so_SO ISO-8859-1",
                "sq_AL.UTF-8 UTF-8",
                "sq_AL ISO-8859-1",
                "sq_MK UTF-8",
                "sr_ME UTF-8",
                "sr_RS UTF-8",
                "sr_RS@latin UTF-8",
                "ss_ZA UTF-8",
                "st_ZA.UTF-8 UTF-8",
                "st_ZA ISO-8859-1",
                "sv_FI.UTF-8 UTF-8",
                "sv_FI ISO-8859-1",
                "sv_FI@euro ISO-8859-15",
                "sv_SE.UTF-8 UTF-8",
                "sv_SE ISO-8859-1",
                "sw_KE UTF-8",
                "sw_TZ UTF-8",
                "syr UTF-8",
                "szl_PL UTF-8",
                "ta_IN UTF-8",
                "ta_LK UTF-8",
                "tcy_IN.UTF-8 UTF-8",
                "te_IN UTF-8",
                "tg_TJ.UTF-8 UTF-8",
                "tg_TJ KOI8-T",
                "th_TH.UTF-8 UTF-8",
                "th_TH TIS-620",
                "the_NP UTF-8",
                "ti_ER UTF-8",
                "ti_ET UTF-8",
                "tig_ER UTF-8",
                "tk_TM UTF-8",
                "tl_PH.UTF-8 UTF-8",
                "tl_PH ISO-8859-1",
                "tn_ZA UTF-8",
                "to_TO UTF-8",
                "tpi_PG UTF-8",
                "tr_CY.UTF-8 UTF-8",
                "tr_CY ISO-8859-9",
                "tr_TR.UTF-8 UTF-8",
                "tr_TR ISO-8859-9",
                "ts_ZA UTF-8",
                "tt_RU UTF-8",
                "tt_RU@iqtelif UTF-8",
                "ug_CN UTF-8",
                "uk_UA.UTF-8 UTF-8",
                "uk_UA KOI8-U",
                "unm_US UTF-8",
                "ur_IN UTF-8",
                "ur_PK UTF-8",
                "uz_UZ.UTF-8 UTF-8",
                "uz_UZ ISO-8859-1",
                "uz_UZ@cyrillic UTF-8",
                "ve_ZA UTF-8",
                "vi_VN UTF-8",
                "wa_BE ISO-8859-1",
                "wa_BE@euro ISO-8859-15",
                "wa_BE.UTF-8 UTF-8",
                "wae_CH UTF-8",
                "wal_ET UTF-8",
                "wo_SN UTF-8",
                "xh_ZA.UTF-8 UTF-8",
                "xh_ZA ISO-8859-1",
                "yi_US.UTF-8 UTF-8",
                "yi_US CP1255",
                "yo_NG UTF-8",
                "yue_HK UTF-8",
                "yuw_PG UTF-8",
                "zh_CN.GB18030 GB18030",
                "zh_CN.GBK GBK",
                "zh_CN.UTF-8 UTF-8",
                "zh_CN GB2312",
                "zh_HK.UTF-8 UTF-8",
                "zh_HK BIG5-HKSCS",
                "zh_SG.UTF-8 UTF-8",
                "zh_SG.GBK GBK",
                "zh_SG GB2312",
                "zh_TW.EUC-TW EUC-TW",
                "zh_TW.UTF-8 UTF-8",
                "zh_TW BIG5",
                "zu_ZA.UTF-8 UTF-8",
                "zu_ZA ISO-8859-1",
            ]),
        }
    }
}
