name: Rust Build and Release

on:
  push:
    branches:
      - rust-rewrite
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: rust-rewrite

    - name: Set up Rust
      uses: ATiltedTree/setup-rust@v1
      with:
          rust-version: stable

    - name: Build
      run: cargo build --release
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: target/release/tui
        tag_name: release-${{ steps.date.outputs.date }}
        release_name: Release ${{ github.event.after }}
        prerelease: true
    - name: upload linux artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./target/release/tui
        asset_name: 2lazy4arch
        asset_content_type: application/x-pie-executable
  # Add additional steps as needed
