name: Rust Build and Release

on:
  push:
    branches:
      - rust-rewrite
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: rust-rewrite

    - name: Set up Rust
      uses: ATiltedTree/setup-rust@v1
      with:
          rust-version: stable

    - name: Build
      run: cargo build --release

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: target/release/tui
        tag_name: ${{ github.ref }}
        asset-name: 2lazy4arch
        release-name: Release ${{ github.event.after }}
        prerelease: true

  # Add additional steps as needed
